## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: "1.0"

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 24

  padding:
    x: 8
    y: 8

  decorations: none
  startup_mode: Windowed
  dynamic_title: true

  ## scrolling
  history: 10000
  multiplier: 3

  ## Background opacity
  opacity: 0.9

## Cursor
cursor:
  style:
    shape: Beam
    blinking: Always

  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
shell:
  program: /usr/bin/fish
#  args:
#    - --login

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "dank mono"
    style: "Light"

  # Bold font face
  bold:
    family: "dank mono"
    style: Book

  # Italic font face
  italic:
    family: "dank mono"
    style: Book Italic

  # Bold italic font face
  bold_italic:
    family: "dank mono"
    style: Italic

  # Point size
  size: 18

  # Offset
  offset:
    x: 0
    y: 0

  # Glyph offset
  #glyph_offset:
  # x: 0
  # y: 0

custom_cursor_colors: true

colors:
  primary:
    background: "0x1d1f21"
    foreground: "0xc5c8c6"
  cursor:
    text: "0x1d1f21"
    cursor: "0xc5c8c6"
  normal:
    black: "0x1d1f21"
    red: "0xcc6666"
    green: "0xb5bd68"
    yellow: "0xf0c674"
    blue: "0x81a2be"
    magenta: "0xb294bb"
    cyan: "0x8abeb7"
    white: "0xc5c8c6"
  bright:
    black: "0x7c7c7c"
    red: "0xff6c6b"
    green: "0x98c379"
    yellow: "0xffd05a"
    blue: "0x8ec07c"
    magenta: "0xff73fd"
    cyan: "0xa9bdbd"
    white: "0xefefef"

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: N, mods: Control|Shift, action: CreateNewWindow }
