## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 24

  padding:
    x: 12
    y: 12

  decorations: none
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 1

## Cursor
cursor:
  style:
    shape: Beam
    blinking: Always

  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
shell:
  program: /usr/bin/fish
#  args:
#    - --login

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "operator mono"
    style: "Light"

  # Bold font face
  bold:
    family: "operator mono"
    style: Book

  # Italic font face
  italic:
    family: "operator mono"
    style: Book Italic

  # Bold italic font face
  bold_italic:
    family: "operator mono"
    style: Italic

  # Point size
  size: 18

  # Offset
  offset:
     x: 0 
     y: 2 

  # Glyph offset
  #glyph_offset:
  #  x: 2 
  #  y: 2

custom_cursor_colors: true

# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Template
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
  footer_bar:
    background: '#282a36'
    foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'


key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: N,         mods: Control|Shift, action: CreateNewWindow }
