## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 24

  padding:
    x: 12
    y: 12

  decorations: none
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 0.9 

## Cursor
cursor:
  style:
    shape: Beam
    blinking: Always

  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
shell:
  program: /usr/bin/fish
#  args:
#    - --login

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "dank mono"
    style: "Light"

  # Bold font face
  bold:
    family: "dank mono"
    style: Book

  # Italic font face
  italic:
    family: "dank mono"
    style: Book Italic

  # Bold italic font face
  bold_italic:
    family: "dank mono"
    style: Italic

  # Point size
  size: 18

  # Offset
  offset:
     x: 0 
     y: 2 

  # Glyph offset
  #glyph_offset:
    #x: 2 
    #y: 2

custom_cursor_colors: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'


key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: N,         mods: Control|Shift, action: CreateNewWindow }
