## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 24

  padding:
    x: 12
    y: 12

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 1.0

## Cursor
cursor:
  style:
    shape: Beam
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
#shell:
#  program: /bin/zsh
#  args:
#    - --login

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "operator mono"
    #style: Regular

  # Bold font face
  bold:
    family: "operator mono"
    #style: Bold

  # Italic font face
  italic:
    family: "operator mono"
    #style: Italic

  # Bold italic font face
  bold_italic:
    family: "operator mono"
    #style: Bold Italic

  # Point size
  size: 15

  # Offset
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
 
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbbbbbb'
 
  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xffffff'

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
